# Generated by Django 5.0.4 on 2024-04-21 09:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModbusTCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='device name')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='description')),
                ('active', models.BooleanField(default=True, help_text='default: True', verbose_name='enabled')),
                ('hostname', models.GenericIPAddressField(default='127.0.0.1', protocol='IPv4', verbose_name='host')),
                ('port', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='port')),
                ('local_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', verbose_name='local address')),
                ('timeout', models.FloatField(default=2000, verbose_name='timeout')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.devicetype', verbose_name='device type')),
            ],
            options={
                'verbose_name': 'Modbus TCP Device',
                'verbose_name_plural': 'Modbus TCP Devices',
            },
        ),
    ]
