# Generated by Django 5.0.4 on 2024-04-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetype',
            name='app_name',
            field=models.CharField(max_length=400, verbose_name='app name'),
        ),
    ]
